export enum Permission {
  // User & Role Management
  MANAGE_USERS = 'MANAGE_USERS',
  MANAGE_ROLES = 'MANAGE_ROLES',
  MANAGE_PERMISSIONS = 'MANAGE_PERMISSIONS',
  MANAGE_SYSTEM_SETTINGS = 'MANAGE_SYSTEM_SETTINGS',

  // Gate Management
  MANAGE_GATES = 'MANAGE_GATES',

  // Blacklist Management
  MANAGE_BLACKLIST = 'MANAGE_BLACKLIST',

  // Entry / Exit Operations
  REGISTER_ENTRY = 'REGISTER_ENTRY',
  REGISTER_EXIT = 'REGISTER_EXIT',

  // Search & View
  SEARCH_RECORDS = 'SEARCH_RECORDS',
  VIEW_DASHBOARD = 'VIEW_DASHBOARD',
  VIEW_REPORTS = 'VIEW_REPORTS',
  VIEW_AUDIT_LOGS = 'VIEW_AUDIT_LOGS',

  // Output
  PRINT_PASSES = 'PRINT_PASSES',
  EXPORT_REPORTS = 'EXPORT_REPORTS',
}
