version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: nestjs-mysql-dev
    ports:
      - '3307:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=nestjs_starter
    volumes:
      - mysql-dev-data:/var/lib/mysql
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h localhost -u root -proot']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - nestjs-dev-network

networks:
  nestjs-dev-network:
    driver: bridge

volumes:
  mysql-dev-data:
